### PR TITLE
add some packages

### PR DESCRIPTION
**Pull request by garak**
I often use wkhtmltopdf with php (via knplabs/knp-snappy) and I'd like to add a few dependencies for it

### CODE REVIEW

**Comment by edbizarro** [comment]
Hi @garak,

First of all, thank you for the interest in this project.

I submitted a new version of the [Dockerfile](https://github.com/edbizarro/bitbucket-pipelines-php7/blob/master/Dockerfile) with some major changes.

Now i'm using an [image](https://github.com/edbizarro/gitlab-ci-pipeline-php) based on official PHP library (Debian), and install mysql on top of that.

About your PR i'm trying not to install specific project dependencies, just the base PHP and some packages need to test Laravel projects, to keep image size small as possible.

To achieve what you need you can install the dependencies in the pipeline run, an example:

```YAML
image: edbizarro/bitbucket-pipelines-php7
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y -qq libxext6 libxrender1 libfontconfig1
          - service mysql start # We need this here because bitbucket don't have MySQL service :/
          - mysql -h localhost -u root -proot -e "CREATE DATABASE test;"
          - composer install --no-interaction --no-progress --prefer-dist          
          - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
```

**Comment by garak** [comment]
Thanks for your suggestion. I just tried to add that line to my pipeline and it looks like the libs are installed, but the db connection is not working anymore :disappointed:
I'm getting `SQLSTATE[HY000] [1130] Host '127.0.0.1' is not allowed to connect to this MySQL server  `

**Comment by edbizarro** [comment]
Change your mysql host config to localhost instead 127.0.0.1

**Comment by garak** [comment]
That's unfair.
Thanks anyway

**Pull request closed without merging**
